[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
sysvar = "aCAT59XoL7QCDCLCE5LmQyeK6dauLtPMDKamt7cSRS5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/localnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
