[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
day_4 = "EabHrNd6S9eftdasCnAiz4zKosGWZcS98upxr5o5xqCf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
